language: python

services: elasticsearch

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

install:
  - pip install -e .

script: python setup.py test

notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
